# Generated by Django 2.2.2 on 2019-06-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20190612_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.CharField(default='low', max_length=50),
            preserve_default=False,
        ),
    ]
