# Generated by Django 2.2.2 on 2019-06-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_card_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='priority',
        ),
    ]
